[diag] Increase DIAG_SIZE_FRONTEND
This was causing an automerger build issue:

```
llvm-project/clang/lib/Basic/DiagnosticIDs.cpp:175:1: error: static assertion failed due to requirement 'static_cast<unsigned int>(diag::NUM_BUILTIN_FRONTEND_DIAGNOSTICS) < static_cast<unsigned int>(diag::DIAG_START_FRONTEND) + static_cast<unsigned int>(diag::DIAG_SIZE_FRONTEND)': DIAG_SIZE_FRONTEND is insufficient to contain all diagnostics, it may need to be made larger in DiagnosticIDs.h.
```

rdar://172125736