[NFC][VPlan][Tests] Some CHECKs cleanup (#211425)
* Fix RUN-line in `VPlan/AArch64/call-decisions.ll` to work with UTC

"; -RUN" was resulting in

```
Error: Failed to update test <...>/call-decisions.ll
Traceback (most recent call last):
  File "<...>/update_analyze_test_checks.py", line 228, in main
    update_test(opt_basename, ti)
  File "<...>/update_analyze_test_checks.py", line 131, in update_test
    check_label_prefix = "VPlan for loop in " if regex == common.VPLAN_RE else ""
UnboundLocalError: local variable 'regex' referenced before assignment
```

* Regenerate CHECKs in VPlan/X86/vplan-vp-intrinsics.ll with UTC

* Split VPlan/interleave-and-scalarize-only.ll in two (VPlan/LLVM dumps)
to be able to use UTC plus use `-vplan-print-metadata=false` for VPlan
version

* Remove stale `CHECK-NOT`

Probably missed in `-debug` -> `-vplan-print-after` transition.

(cherry picked from commit a443ddb9b096aff4a0c9dea18df4e2ce6bc7bc85)