[lldb] Prevent mutation of CommandAlias::GetOptionArguments (#6806)
Fix a mutation of `CommandAlias::m_option_args_sp`, which resulted in cases where
aliases would fail to run on second, and subsequent times.

For example, an alias such as:

```
command alias p1 p 1
```

When run the second time, the following error would be reported to the user:

```
error: expression failed to parse:
error: <user expression 1>:1:1: expression is not assignable
--  1
^   ~
```

To fix this, `CommandAlias::Desugar` now constructs options to a freshly constructed
vector, rather than by appending to the results of `GetOptionArguments`.

rdar://107770836

Differential Revision: https://reviews.llvm.org/D150078

(cherry picked from commit 765237779ce4dbb60f4faf9ebc91386ce5218e15)


(cherry-picked from commit d384c3747fab25c230752c9c107efdfa9c183d60)