[clang-cache] Report scan diagnostics (#9035)
Diagnostics from dependency scanning daemon aren't making their way to the end-user and the feedback is vague:
```
fatal error: CAS-based dependency scan failed: depscan daemon failed: failed to get include-tree
```

This patch extends the daemon protocol to send the diagnostics back and prints them to standard error output.

rdar://116549128
(cherry picked from commit 2fdda439c91853b0ba149c466d14ffa9f1ea5d3b)