[BoundsSafety][LLDB] Try to Fix `bounds_safety_soft_trap*_missing_reason` tests on Linux
The tests were failing with:

```
/home/build-user/llvm-project/lldb/test/Shell/BoundsSafety/Inputs/boundsSafetySoftTrapsMissingReason.c:5:32: error: a parameter list without types is only allowed in a function definition
    5 | int bad_call(int *__counted_by(count) ptr, int count) {}
      |                                ^
/home/build-user/llvm-project/lldb/test/Shell/BoundsSafety/Inputs/boundsSafetySoftTrapsMissingReason.c:5:39: error: expected ')'
    5 | int bad_call(int *__counted_by(count) ptr, int count) {}
      |                                       ^
/home/build-user/llvm-project/lldb/test/Shell/BoundsSafety/Inputs/boundsSafetySoftTrapsMissingReason.c:5:13: note: to match this '('
    5 | int bad_call(int *__counted_by(count) ptr, int count) {}
      |             ^
2 errors generated.
```

This is happening because `__counted_by` is a macro but the `ptrcheck.h`
header that defines it is not included. This wasn't caught on macOS
because the Libc headers on that platform automatically include that
header.

I don't have a Linux VM to hand so this is a speculative fix that should
fix the include issue.

rdar://165202129