[lldb] Re-enable TestSwiftRegex (#6798)
To evaluate the command `expr -O -- regex`, the target triple needs to specify macOS 13 
or greater. The underlying issue should have been an error when `main.swift` was being 
compiled, but `-disable-availability-checking` was being used. As it was, the 
expression evaluation would result in this error (which was only seen in the logs):

> error: 'Regex' is only available in macOS 13.0 or newer

While debugging the issue, the use of `v`/`vo`/`expr`/`expr -O` were split out into 
separate test functions. Interestingly `vo` will succeed even in the case where `expr 
-O` did not.

This reverts commit de23e7653f890619c7263c7d8c2466ecc7dba941.

rdar://106107613

(cherry-picked from commit f18ed27ef0d8ec67128989830b9646aa02c649dc)