[lldb] Declare argument to `swift demangle` (#6830)
Without an argument declaration, lldb reports:

```
error: 'demangle' doesn't take any arguments.
```

rdar://104190981

(cherry-picked from commit bfa3a2c7433cace436854216f952a2a9ee5f4d07)