[BoundsSafety] Add missing `CursorKind` for some `-fbounds-safety` specific Expr kinds
This fixes running the `ninja check-clang-python` target that previously
failed with:

```
.....................................................................................F.................................................................................
======================================================================
FAIL: test_all_variants (tests.cindex.test_enums.TestEnums.test_all_variants) [<enum 'CursorKind'>]
Check that all libclang enum values are also defined in cindex.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/user_data/dev/llvm/upstream_swift/next/src/llvm-project/clang/bindings/python/tests/cindex/test_enums.py", line 87, in test_all_variants
    self.assertEqual(
AssertionError: {'CXCursor_ForgePtrExpr', 'CXCursor_LastExpr'} variants are missing. Please ensure these are defined in <enum 'CursorKind'> in cindex.py.
```

rdar://161075623