Handle tag types and complain about bad merges in C/Objective-C mode
Take `struct Z {...}` defined differently and imported from both modules
X and Y. While in C/Objective-C mode, clang used to pick one of the
definitions and ignore the other even though they are not structurally
equivalent. Hook up a mechanism to check for it and reject such
conflicts. Instead of silently compiling, clang now emits:

In module 'Y' imported from t.m:2:
./y.h:2:8: error: type 'struct Z' has incompatible definitions in different translation units
struct Z {
       ^
./y.h:3:10: note: field 'm' has type 'double' here
  double m;
         ^
./x.h:3:7: note: field 'm' has type 'int' here
  int m;
      ^

rdar://problem/56764293